### ISSUE TITLE
[PREGUNTA] Especificaciones técnicas para leer cedulas nuevas con QR.

### ISSUE THREAD

**Issue by rvega** [Eitol/colombian-cedula-reader#1]
Hola, muchas gracias por publicar este repositorio, muy útil!

En el README se menciona que se está desarrollando el soporte para cédulas nuevas con QR.  Me podrían decir dónde hay información técnica de cómo se léen esos códigos QR?

Gracias!

**Comment by Eitol** [comment]
Hola, al final no se pudo descifrar esos QRs, eran demasiado densos y cuando se leían arrojaban información encriptada. Para las cédulas nuevas lo que pude hacer fue leer el mrz. Ahí en el readme está el link al otro repo que contiene esa funcionalidad
